// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD28Jrl3sX86XDmy6fk8tQ4nAQnH7BEGPs',
    appId: '1:175829270253:web:a5287257ffba23efdf16e4',
    messagingSenderId: '175829270253',
    projectId: 'fintech-registration-app',
    authDomain: 'fintech-registration-app.firebaseapp.com',
    storageBucket: 'fintech-registration-app.appspot.com',
    measurementId: 'G-N46WHWXQCD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2zyXRIbSJczc4RT1UYn7djCmxgZjt5Jk',
    appId: '1:175829270253:android:e1060a1b65fb33bfdf16e4',
    messagingSenderId: '175829270253',
    projectId: 'fintech-registration-app',
    storageBucket: 'fintech-registration-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ1Vi39P5LPEHTfk2FZXLzrU3DGChs7qg',
    appId: '1:175829270253:ios:d82a07e42284dc63df16e4',
    messagingSenderId: '175829270253',
    projectId: 'fintech-registration-app',
    storageBucket: 'fintech-registration-app.appspot.com',
    iosClientId: '175829270253-2n9hjfb2o06u7jgo7vk1jbigsq134lfu.apps.googleusercontent.com',
    iosBundleId: 'com.ibcm.fintechRegistrationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ1Vi39P5LPEHTfk2FZXLzrU3DGChs7qg',
    appId: '1:175829270253:ios:d82a07e42284dc63df16e4',
    messagingSenderId: '175829270253',
    projectId: 'fintech-registration-app',
    storageBucket: 'fintech-registration-app.appspot.com',
    iosClientId: '175829270253-2n9hjfb2o06u7jgo7vk1jbigsq134lfu.apps.googleusercontent.com',
    iosBundleId: 'com.ibcm.fintechRegistrationApp',
  );
}
